import type { EnemyDef } from "./types.js";

export const ENEMIES: Record<string, EnemyDef> = {
  flyer: {
    id: "flyer",
    name: "Cursed Flyer",
    hp: 8,
    speed: 140,
    damage: 5,
    xp: 2,
    radius: 12,
    color: 0x7b5cff,
  },
  charger: {
    id: "charger",
    name: "Charger Spirit",
    hp: 20,
    speed: 260,
    damage: 12,
    xp: 5,
    radius: 16,
    color: 0xff5c5c,
  },
  swarm: {
    id: "swarm",
    name: "Swarm Wisp",
    hp: 4,
    speed: 100,
    damage: 3,
    xp: 1,
    radius: 8,
    color: 0xa855f7,
  },
  tank: {
    id: "tank",
    name: "Grade 2 Tank",
    hp: 80,
    speed: 70,
    damage: 18,
    xp: 15,
    radius: 22,
    color: 0x4a5568,
  },
  ranged: {
    id: "ranged",
    name: "Ranged Curse",
    hp: 15,
    speed: 90,
    damage: 8,
    xp: 6,
    radius: 14,
    color: 0x22d3ee,
  },
  exploder: {
    id: "exploder",
    name: "Volatile Spirit",
    hp: 12,
    speed: 120,
    damage: 25,
    xp: 8,
    radius: 13,
    color: 0xfbbf24,
  },
  elite_grade1: {
    id: "elite_grade1",
    name: "Grade 1 Elite",
    hp: 200,
    speed: 110,
    damage: 22,
    xp: 50,
    radius: 28,
    color: 0xc084fc,
    isElite: true,
  },
  elite_grade2: {
    id: "elite_grade2",
    name: "Semi-Grade 1",
    hp: 350,
    speed: 95,
    damage: 30,
    xp: 80,
    radius: 32,
    color: 0x818cf8,
    isElite: true,
  },
  elite_grade3: {
    id: "elite_grade3",
    name: "Special Threat",
    hp: 500,
    speed: 85,
    damage: 38,
    xp: 120,
    radius: 36,
    color: 0xf472b6,
    isElite: true,
  },
  boss_jogo: {
    id: "boss_jogo",
    name: "Volcanic Special Grade",
    hp: 8000,
    speed: 60,
    damage: 45,
    xp: 500,
    radius: 48,
    color: 0xef4444,
    isBoss: true,
  },
  // New bosses for Tier 1 #4. Same art for now (reuses enemy_boss_jogo
  // texture) with palette tints; differentiated by stats + special patterns.
  boss_hanami: {
    id: "boss_hanami",
    name: "Verdant Special Grade",
    hp: 9000,
    speed: 55,
    damage: 38,
    xp: 600,
    radius: 50,
    color: 0x14532d,
    isBoss: true,
  },
  boss_mahito: {
    id: "boss_mahito",
    name: "Soul Sculptor",
    hp: 7500,
    speed: 80,
    damage: 50,
    xp: 700,
    radius: 44,
    color: 0xbe185d,
    isBoss: true,
  },
  // ── Villain roster ──────────────────────────────────────────────────
  // King of Curses — biggest HP pool, hardest hitting. Sits at the top
  // of the boss difficulty curve.
  boss_sukuna: {
    id: "boss_sukuna",
    name: "King of Curses",
    hp: 12000,
    speed: 75,
    damage: 60,
    xp: 900,
    radius: 52,
    color: 0xb91c1c,
    isBoss: true,
  },
  // Cursed Spirit Manipulator — moderate stats, big crowd-management vibe.
  // Slightly faster than the average boss; lots of XP for the kill.
  boss_geto: {
    id: "boss_geto",
    name: "Cursed Spirit Manipulator",
    hp: 9500,
    speed: 95,
    damage: 42,
    xp: 750,
    radius: 46,
    color: 0x4338ca,
    isBoss: true,
  },
  // The Sorcerer Killer — heavenly restriction physical brute. Fast,
  // hits hard, but smaller HP — punishes slow players.
  boss_toji: {
    id: "boss_toji",
    name: "Sorcerer Killer",
    hp: 8000,
    speed: 130,
    damage: 70,
    xp: 800,
    radius: 42,
    color: 0x1f2937,
    isBoss: true,
  },
};

export const BOSS_IDS = [
  "boss_jogo",
  "boss_hanami",
  "boss_mahito",
  "boss_sukuna",
  "boss_geto",
  "boss_toji",
] as const;

export const TRASH_ENEMY_IDS = [
  "flyer",
  "charger",
  "swarm",
  "tank",
  "ranged",
  "exploder",
] as const;
